### ISSUE TITLE
[pgadmin4] Works OK with port forward, but error on login with ingress

### ISSUE THREAD

**Issue by jschaeff** [rowanruseler/helm-charts#163]
First, thank you for this helpfull helm chart. Great work, nicely customizable.

The deployment works well when I access pgadmin4 wit a port-forward. But accessing it through an ingress rule, after login I only get a json file: 

```json
{"success":0,"errormsg":"'NoneType' object has no attribute 'decode'","info":"","result":null,"data":null}
```
The pod log shows:

```
2022-08-17 05:51:05,868: ERROR	pgadmin:	'NoneType' object has no attribute 'decode'
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/pgadmin4/pgadmin/authenticate/__init__.py", line 99, in login
    if not auth_obj.validate():
  File "/pgadmin4/pgadmin/authenticate/__init__.py", line 222, in validate
    status, err_msg = source.validate(self.form)
  File "/pgadmin4/pgadmin/authenticate/internal.py", line 101, in validate
    if not validate_email(form.data['email']):
  File "/pgadmin4/pgadmin/utils/validation_utils.py", line 18, in validate_email
    valid = email_validate(
  File "/venv/lib/python3.9/site-packages/email_validator/__init__.py", line 281, in validate_email
    email = email.decode("ascii")
AttributeError: 'NoneType' object has no attribute 'decode'
```

I tried several options for ``ingress.hosts.host[0].path`` but always the same result.

Any idea on what's wrong ?

**Comment by tirelibirefe** [comment]
Hello @jschaeff 
Were you able to fix the problem?

**Comment by jschaeff** [comment]
No, I worked a lot on it and could'nt get the right settings.

I have similar issues with other deployments and ingresses. So the problem may not be related to the chart.

I'd be glad to test any suggestion, though.

**Comment by rowanruseler** [comment]
Sorry for the very late reply, but do you perhaps have your ingress part for me? So I can try and reproduce it.

**Comment by jschaeff** [comment]
Hello, thanks for taking the time.

There is my ingress:

```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin
spec:
  rules:
    - host: pgadmin.resif.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pgadmin-service
                port:
                  number: 80

**Comment by cobcan** [comment]
Hi, I've just created an issue with this, the problem is in the values.yaml the in .ingress.ClassName should be .ingress.ingressClassName.

```yaml
ingress:
  enabled: true
  ingressClassName: "example"
```

**Comment by sahil-sharma** [comment]
Same issue for me. With port-forward it does work while with Ingress path it fails.
I have set `contextPath: "/pgadmin4"` and here is my ingress block in my values file:
```
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Script-Name /pgadmin4;
      proxy_set_header X-Forwarded-Prefix /pgadmin4;
    #nginx.ingress.kubernetes.io/proxy-redirect-from: "~^http://([^/]+)/(pgadmin4/)?(.*)$"
    #nginx.ingress.kubernetes.io/rewrite-target: /pgadmin4/
    #nginx.ingress.kubernetes.io/proxy-redirect-to: "http://$1/pgadmin4/$3"
    #nginx.ingress.kubernetes.io/enable-cors: "true"
    #nginx.ingress.kubernetes.io/cors-allow-origin: "http://pgadmin.local"
  hosts:
    - host: pgadmin.local
      paths:
        - path: /pgadmin4
          pathType: ImplementationSpecific
```
I have tried all the possible options but it just fails. I have also tried [this](https://github.com/rowanruseler/helm-charts/blob/main/charts/pgadmin4/examples/ingress-with-outside-tls-termination.yaml) but it too did not work.
Any ideas on this would be helpful.

**Comment by sahil-sharma** [comment]
@cobcan I think it is already there:
https://github.com/rowanruseler/helm-charts/blob/main/charts/pgadmin4/values.yaml#L142

**Comment by rowanruseler** [comment]
`ingress.ingressClassName` exists, and the default NetworkPolicy allows any source. Does the login error still happen on 1.68.9, starting from `examples/ingress-with-outside-tls-termination.yaml`? Closing in a few weeks without a reply.
