### ISSUE TITLE
Permission denied: '/var/lib/pgadmin/sessions'

### ISSUE THREAD

**Issue by cemsusal** [rowanruseler/helm-charts#32]
**Describe the bug**

Having permission denied error on startup for the pod pgadmin4-xxxx.

**Version of Helm and Kubernetes**:

Kubernetes: 1.18.3 - Running on Premise
Helm: 3.2.3

**Which chart**:

 runix/pgadmin4

**What happened**:

Installed the chart with the following command.

helm upgrade --install --namespace xxxx \
--set env.email=<my email address> \ 
--set env.password=<my password> \
--set persistentVolume.enabled=true \
--set persistentVolume.storageClass=<storage class name> \
--set persistentVolume.size=2Gi \
--set service.type=ClusterIP \
--set ingress.enabled=false \
pgadmin runix/pgadmin4

The chart has been installed successfully but the app crashed with the following errors:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/gthread.py", line 104, in init_process
    super(ThreadWorker, self).init_process()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/pgadmin4/run_pgadmin.py", line 4, in <module>
    from pgAdmin4 import app
  File "/pgadmin4/pgAdmin4.py", line 92, in <module>
    app = create_app()
  File "/pgadmin4/pgadmin/__init__.py", line 241, in create_app
    create_app_data_directory(config)
  File "/pgadmin4/pgadmin/setup/data_directory.py", line 40, in create_app_data_directory
    _create_directory_if_not_exists(config.SESSION_DB_PATH)
  File "/pgadmin4/pgadmin/setup/data_directory.py", line 16, in _create_directory_if_not_exists
    os.mkdir(_path)
PermissionError: [Errno 13] Permission denied: '/var/lib/pgadmin/sessions'
[2020-06-18 13:07:36 +0000] [91] [INFO] Worker exiting (pid: 91)
WARNING: Failed to set ACL on the directory containing the configuration database: [Errno 1] Operation not permitted: '/var/lib/pgadmin'
/usr/local/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  return io.open(fd, *args, **kwargs)
[2020-06-18 13:07:36 +0000] [1] [INFO] Shutting down: Master
[2020-06-18 13:07:36 +0000] [1] [INFO] Reason: Worker failed to boot.

**Comment by rowanruseler** [comment]
Could you enable the following, and see if it works?
```
VolumePermissions:
  ## If true, enables an InitContainer to set permissions on /var/lib/pgadmin.
  ## 
  enabled: false
```

**Comment by cemsusal** [comment]
It works now. Thanks a lot for your help.
